# This is a basic workflow to help you get started with Actions

name: Deploy HTML

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3          
        with:
          persist-credentials: false
          # submodules: true  # Fetch submodules (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install git-restore-mtime
          pip3 install -r requirements.txt
          chmod +x ./cli.py
        
      - name: Install latexml Dependencies
        run: > 
          sudo apt-get install
          cpanminus
          libarchive-zip-perl
          libdb-dev
          libfile-which-perl
          libimage-magick-perl
          libimage-size-perl
          libio-string-perl
          libjson-xs-perl
          libparse-recdescent-perl
          libtext-unidecode-perl
          liburi-perl
          libuuid-tiny-perl
          libwww-perl
          libxml-libxml-perl
          libxml-libxslt-perl
          libxml2
          libxml2-dev
          libxslt1-dev
          libxslt1.1

      - name: Install latexml
        run: "cpanm --notest --sudo https://github.com/brucemiller/LaTeXML/tarball/v0.8.5"


      - name: checkout public repo
        uses: actions/checkout@v3
        with:
          repository: Mannheim-Probability/Probability-Theory
          ref: html # branch html
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
          path: public
          fetch-depth: 0 # Fetch entire history
      
      - name: Restore Mtime for caching
        run: |
          cd public 
          git restore-mtime --verbose
          git diff --name-only HEAD

      - name: Build Webpage
        run: ./cli.py make-website

      - name: Push
        run: |
          cd public
          git config --local user.name "Github Action"
          git config --local user.email "noreply.actions@github.com"
          git add --all
          git diff-index --quiet HEAD || git commit -m $GITHUB_SHA
          git push git@github.com:Mannheim-Probability/Probability-Theory.git
          