# This is a basic workflow to help you get started with Actions

name: Make PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "make-pdfs"
  make-pdfs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name:
        - Exercises
        - Solutions
        include:
        - name: Exercises
          solutions: "--hide"
        - name: Solutions
          solutions: "--show"
        
      fail-fast: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Hide Solutions 
        run: | 
          pip3 install -r requirements.txt
          chmod +x cli.py 
          ./cli.py solutions ${{ matrix.solutions }}

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: "sheet_*.tex"
          glob_root_file: true
      
      - name: move outputs to folder
        run: |
          mkdir out
          mv *.pdf ./out
      
      - name: append _solution suffix
        if: contains(matrix.name, 'Solutions')
        run: for f in out/*.pdf; do mv -- "$f" "${f%.pdf}_solution.pdf"; done

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: ${{ matrix.name }} 
          # A file, directory or wildcard pattern that describes what to upload
          path: "out" 
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 0 # optional
